### PR TITLE
removed support for debian 9 and 10

### PR DESCRIPTION
**Pull request by FrankreedX**

### CODE REVIEW

**Review by ramereth — APPROVED** [review]
Please do a patch bump.

**Comment by FrankreedX** [comment]
!bump minor

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.1.0.  Have a nice day!

**Comment by ramereth** [comment]
@FrankreedX you forgot to add `~` at the end so it didn't create an environment bump PR. I'll do this manually but wanted to give you a heads up.

**Pull request merged**
