### PR TITLE
Add Debian 12 support

### PR DESCRIPTION
**Pull request by justinswe**
PR for adding Debian 12 OS support to this cookbook. Rspec/unit testing should be complete which was confirmed on my local by using the fauxhai branch which supports Debian 12(not merged yet).

### CODE REVIEW

**Comment by ramereth** [comment]
LGTM

**Review by ramereth — APPROVED** [review]
Patch bump

**Comment by justinswe** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.1.1.  Have a nice day!

**Pull request merged**
