### PR TITLE
Update apt for amd64

### PR DESCRIPTION
**Pull request by justinswe**

### CODE REVIEW

**Review by ramereth — CHANGES_REQUESTED** [review]
Please update the unit tests

**Comment by justinswe** [comment]
> Please update the unit tests

Was working on that as I published; Pushed the changes

**Review by ramereth — APPROVED** [review]
Patch bump

**Comment by justinswe** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.1.2.  Have a nice day!

**Pull request merged**
